export const CAPABILITY = {
  CONTENT_READ: "CONTENT_READ",
  CONTENT_CREATE: "CONTENT_CREATE",
  CONTENT_EDIT: "CONTENT_EDIT",
  CONTENT_REVIEW: "CONTENT_REVIEW",
  CONTENT_PUBLISH: "CONTENT_PUBLISH",
  CONTENT_LEGAL: "CONTENT_LEGAL",
  CATEGORY_MANAGE: "CATEGORY_MANAGE",
  HOMEPAGE_MANAGE: "HOMEPAGE_MANAGE",
  STAFF_MANAGE: "STAFF_MANAGE",
} as const;

export type Capability = (typeof CAPABILITY)[keyof typeof CAPABILITY];

export const CAPABILITIES = [
  CAPABILITY.CONTENT_READ,
  CAPABILITY.CONTENT_CREATE,
  CAPABILITY.CONTENT_EDIT,
  CAPABILITY.CONTENT_REVIEW,
  CAPABILITY.CONTENT_PUBLISH,
  CAPABILITY.CONTENT_LEGAL,
  CAPABILITY.CATEGORY_MANAGE,
  CAPABILITY.HOMEPAGE_MANAGE,
  CAPABILITY.STAFF_MANAGE,
] as const;
