export const PUBLICATION_STATUS = {
  NEVER_PUBLISHED: "NEVER_PUBLISHED",
  PUBLISHED: "PUBLISHED",
  UNPUBLISHED: "UNPUBLISHED",
} as const;

export type PublicationStatus =
  (typeof PUBLICATION_STATUS)[keyof typeof PUBLICATION_STATUS];

export const PUBLICATION_STATUSES = [
  PUBLICATION_STATUS.NEVER_PUBLISHED,
  PUBLICATION_STATUS.PUBLISHED,
  PUBLICATION_STATUS.UNPUBLISHED,
] as const;
