import { CAPABILITY, type Capability } from "./capability";
import { STAFF_ROLE, type StaffRole } from "./staff-role";

const ALL_CAPABILITIES = [
  CAPABILITY.CONTENT_READ,
  CAPABILITY.CONTENT_CREATE,
  CAPABILITY.CONTENT_EDIT,
  CAPABILITY.CONTENT_REVIEW,
  CAPABILITY.CONTENT_PUBLISH,
  CAPABILITY.CATEGORY_MANAGE,
  CAPABILITY.HOMEPAGE_MANAGE,
  CAPABILITY.STAFF_MANAGE,
] as const satisfies readonly Capability[];

export const ROLE_CAPABILITIES: Record<StaffRole, readonly Capability[]> = {
  [STAFF_ROLE.SUPER_ADMIN]: ALL_CAPABILITIES,
  [STAFF_ROLE.EDITOR]: [
    CAPABILITY.CONTENT_READ,
    CAPABILITY.CONTENT_CREATE,
    CAPABILITY.CONTENT_EDIT,
    CAPABILITY.CONTENT_REVIEW,
    CAPABILITY.CONTENT_PUBLISH,
  ],
  [STAFF_ROLE.AUTHOR]: [
    CAPABILITY.CONTENT_READ,
    CAPABILITY.CONTENT_CREATE,
    CAPABILITY.CONTENT_EDIT,
  ],
};
