export const PUBLISHING_ERROR = {
  CONTENT_NOT_FOUND: "CONTENT_NOT_FOUND",
  VERSION_NOT_FOUND: "VERSION_NOT_FOUND",
  VERSION_NOT_OWNED_BY_ITEM: "VERSION_NOT_OWNED_BY_ITEM",
  CONTENT_DELETED: "CONTENT_DELETED",
  INVALID_SLUG: "INVALID_SLUG",
  SLUG_CONFLICT: "SLUG_CONFLICT",
  DRAFT_ALREADY_EXISTS: "DRAFT_ALREADY_EXISTS",
  NO_REVISION_SOURCE: "NO_REVISION_SOURCE",
  INVALID_WORKFLOW_TRANSITION: "INVALID_WORKFLOW_TRANSITION",
  VERSION_NOT_CURRENT_DRAFT: "VERSION_NOT_CURRENT_DRAFT",
  VERSION_NOT_APPROVED: "VERSION_NOT_APPROVED",
  VERSION_NOT_EDITABLE: "VERSION_NOT_EDITABLE",
  INVALID_PUBLISH_TARGET: "INVALID_PUBLISH_TARGET",
  PUBLISH_READINESS_FAILED: "PUBLISH_READINESS_FAILED",
  NOT_PUBLISHED: "NOT_PUBLISHED",
  ALREADY_SCHEDULED: "ALREADY_SCHEDULED",
  NO_SCHEDULE: "NO_SCHEDULE",
  SCHEDULE_NOT_IN_FUTURE: "SCHEDULE_NOT_IN_FUTURE",
  CANNOT_SCHEDULE_PUBLISHED_VERSION: "CANNOT_SCHEDULE_PUBLISHED_VERSION",
  STALE_SCHEDULE_GENERATION: "STALE_SCHEDULE_GENERATION",
  DUPLICATE_RELATION: "DUPLICATE_RELATION",
  MULTIPLE_PRIMARY_CATEGORIES: "MULTIPLE_PRIMARY_CATEGORIES",
  MULTIPLE_HERO_MEDIA: "MULTIPLE_HERO_MEDIA",
  INVALID_RELATION: "INVALID_RELATION",
  RELATION_NOT_FOUND: "RELATION_NOT_FOUND",
  INVALID_HERO_MEDIA: "INVALID_HERO_MEDIA",
  INVALID_GALLERY_MEDIA: "INVALID_GALLERY_MEDIA",
  CONTENT_WRITE_CONFLICT: "CONTENT_WRITE_CONFLICT",
  INVALID_TITLE: "INVALID_TITLE",
  INVALID_BODY: "INVALID_BODY",
  INVALID_URL: "INVALID_URL",
  SELECTED_SCOPE_PRIMARY_REQUIRED: "SELECTED_SCOPE_PRIMARY_REQUIRED",
  CATEGORY_OUT_OF_SCOPE: "CATEGORY_OUT_OF_SCOPE",
  INVALID_REVIEW_NOTE: "INVALID_REVIEW_NOTE",
  CONTENT_BODY_CORRUPT: "CONTENT_BODY_CORRUPT",
} as const;

export type PublishingErrorCode =
  (typeof PUBLISHING_ERROR)[keyof typeof PUBLISHING_ERROR];

export class PublishingError extends Error {
  readonly code: PublishingErrorCode;

  constructor(code: PublishingErrorCode, message: string = code) {
    super(message);
    this.name = "PublishingError";
    this.code = code;
  }
}

export type PublishingDecision<T> =
  | { ok: true; value: T }
  | { ok: false; code: PublishingErrorCode };
