export const REVIEW_EVENT_TYPE = {
  SUBMITTED: "SUBMITTED",
  APPROVED: "APPROVED",
  CHANGES_REQUESTED: "CHANGES_REQUESTED",
} as const;

export type ReviewEventType =
  (typeof REVIEW_EVENT_TYPE)[keyof typeof REVIEW_EVENT_TYPE];

export const REVIEW_EVENT_TYPES = [
  REVIEW_EVENT_TYPE.SUBMITTED,
  REVIEW_EVENT_TYPE.APPROVED,
  REVIEW_EVENT_TYPE.CHANGES_REQUESTED,
] as const;
